# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tianshan.github.io" # the base hostname & protocol for your site

imageurl: "/images"
uploads: "/uploads"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "tianshan"
      email: "qutianshan0214@163.com"

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: 我的博客
  avatar: 
  gravatar: # email md5 hash
  description: "tianshan's blog" # used by search engines

  # Header and footer text
  footer_text: Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: qutianshan0214@163.com # full email address, e.g. "sam@example.com"
  dribbble: 
  facebook: 
  flickr: 
  github: "tianshan"
  google_plus: 
  instagram: 
  linkedin:  # full URL
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange:  # full URL
  twitter: 
  wordpress: 
  youtube: 

  # Scripts
  google_analytics: UA-60561225-1 # tracking id, e.g. "UA-000000-01"
  disqus_shortname: tianshan

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colors, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments

sass:
  sass_dir: _sass
  style: :compressed